version: "3"
services:
  mysql:
    image: mysql:8.0.29
    container_name: mysql
    ports:
     - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      TZ: "Asia/Seoul"
    command:
     - --character-set-server=utf8mb4
     - --collation-server=utf8mb4_unicode_ci
    volumes:
     - /home/ubuntu/docker/data/mysql:/var/lib/mysql
  backend:
    container_name: backend
    build:
      context: ./backend
    command: python manage.py runserver 0:8000
    volumes:
     - ./backend:/backend
    restart: always
    ports:
     - "8000:8000"
    depends_on:
     - mysql

