version: "3"
services:
  mysql:
    image: mysql:latest 
    container_name: mysql 
    ports: 
      - "3306:3306" 
    restart: always 
    environment: 
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: NCTE_database
      MYSQL_PASSWORD: "0000"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
    - /mysql/db:/var/lib/mysql

  backend:
    command: bash
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    links:
      - mysql:mysql
    depends_on:
      - mysql
    restart: always
    volumes:
      - ./backend:/app
    stdin_open: true
    tty: true

